model:
  name: DeepONet
  params:
    layer_sizes_branch: [101, 100, 100]
    layer_sizes_trunk: [2, 100, 100, 100]
    activation: gelu
    kernel_initializer: Glorot normal

  input_transform: ~
  
  output_transform:
    name: dirichlet_Deeponet
    params:
      scale_factor: 10

train:
  batch_size: 5000
  iters: 10000
  max_save: 1
  init_train_size: 50
  final_train_size: 250
  test_size: 1000

active:
  iters: 1000
  funcs: 1000
  select: 1

solver:
  name: diffusion_reaction_solver
  params:
    xmax: 1.0
    tmax: 1.0
    D: 0.01
    k: 0.01
    Nx: 101
    Nt: 101
  
datasets:
  workdir: ./data/dr
  pretrain_path: ~
  train_path: ~
  test_path: ~
  